package com.legaltrack.enums;

public enum LegalAidCategory {
    WOMAN_OR_CHILD,
    SCHEDULED_CASTE_OR_TRIBE,
    PERSON_WITH_DISABILITY,
    INDUSTRIAL_WORKMAN,
    PERSON_IN_CUSTODY,
    VICTIM_OF_TRAFFICKING_OR_BEGAR,
    VICTIM_OF_DISASTER,
    LOW_INCOME_GENERAL,
    OTHER_ELIGIBLE_CATEGORY
}
