package com.legaltrack.enums;

public enum NotificationType {
    HEARING_REMINDER,
    CASE_UPDATE,
    CASE_ATTENTION,
    ORDER_AVAILABLE,
    LAWYER_REQUEST,
    LAWYER_REQUEST_ACCEPTED,
    LAWYER_REQUEST_REJECTED,
    LEGAL_AID_UPDATE,
    DOCUMENT_UPLOADED,
    DOCUMENT_REQUESTED,
    MESSAGE_RECEIVED,
    SUPPORT_UPDATE,
    SYSTEM_ALERT
}
